name: Release

on:
 push:
  branches: 
   - main
   
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: justincy/github-action-npm-release@2.0.2
        id: release
