name: Release

on:
 push:
  branches: 
   - main
   
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: halvardssm/github-action-tag-release@1.0.0
        id: release
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo 'Release created: ${{steps.version.outputs.release_created}}'
          echo 'Release exists: ${{steps.version.outputs.release_exists}}'
          echo 'Release tag: ${{steps.version.outputs.release_tag}}'
